/** Central route paths — keep navigation consistent across layouts. */

export const PATHS = {
  home: '/',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  privacy: '/privacy',
  terms: '/terms',

  masterLogin: '/master/login',
  masterDashboard: '/master/dashboard',
  masterRegistrationRequests: '/master/registration-requests',
  masterTrials: '/master/trials',
  masterPlans: '/master/plans',
  masterBusinesses: '/master/businesses',
  masterAudit: '/master/audit',
  masterTrialSettings: '/master/settings/trial',
  masterChangePassword: '/master/change-password',

  ownerDashboard: '/owner/dashboard',
  ownerBills: '/owner/bills',
  ownerItems: '/owner/items',
  ownerItemActivity: '/owner/item-activity',
  ownerStockMovements: '/owner/stock-movements',
  ownerCategories: '/owner/categories',
  ownerCustomers: '/owner/customers',
  ownerSuppliers: '/owner/suppliers',
  ownerPurchases: '/owner/purchases',
  ownerExpenses: '/owner/expenses',
  ownerTables: '/owner/tables',
  ownerMenu: '/owner/menu',
  ownerOrders: '/owner/orders',
  ownerOrdersNew: '/owner/orders/new',
  ownerKitchen: '/owner/kitchen',
  ownerCafe: '/owner/cafe',
  ownerGrocery: '/owner/grocery',
  ownerStationery: '/owner/stationery',
  ownerHardware: '/owner/hardware',
  ownerClothing: '/owner/clothing',
  ownerReturns: '/owner/returns',
  ownerRepairs: '/owner/repairs',
  ownerInstallations: '/owner/installations',
  ownerDeliveries: '/owner/deliveries',
  ownerQuotations: '/owner/quotations',
  ownerPriceLists: '/owner/price-lists',
  ownerSalesOrders: '/owner/sales-orders',
  ownerPurchaseOrders: '/owner/purchase-orders',
  ownerChallans: '/owner/challans',
  ownerWarehouses: '/owner/warehouses',
  ownerTourPackages: '/owner/tour-packages',
  ownerTravelBookings: '/owner/travel-bookings',
  ownerTravelAgents: '/owner/travel-agents',
  ownerBatches: '/owner/batches',
  ownerCredit: '/owner/credit',
  ownerOutstanding: '/owner/outstanding',
  ownerRecipes: '/owner/recipes',
  ownerProduction: '/owner/production',
  ownerCakeOrders: '/owner/cake-orders',
  ownerFurnitureOrders: '/owner/furniture-orders',
  ownerWastage: '/owner/wastage',
  ownerVariants: '/owner/variants',
  ownerSerials: '/owner/serials',
  ownerReports: '/owner/reports',
  ownerAi: '/owner/ai',
  ownerAudit: '/owner/audit',
  ownerUsers: '/owner/users',
  ownerSettings: '/owner/settings',
  ownerProfile: '/owner/profile',
  ownerChangePassword: '/owner/change-password',

  billingHome: '/billing',
  billingNew: '/billing/new',
  billingBills: '/billing/bills',
  billingItems: '/billing/items',
  billingCategories: '/billing/categories',
  billingCustomers: '/billing/customers',
  billingSuppliers: '/billing/suppliers',
  billingPurchases: '/billing/purchases',
  billingExpenses: '/billing/expenses',
  billingTables: '/billing/tables',
  billingMenu: '/billing/menu',
  billingOrders: '/billing/orders',
  billingOrdersNew: '/billing/orders/new',
  billingKitchen: '/billing/kitchen',
  billingCafe: '/billing/cafe',
  billingGrocery: '/billing/grocery',
  billingStationery: '/billing/stationery',
  billingHardware: '/billing/hardware',
  billingClothing: '/billing/clothing',
  billingReturns: '/billing/returns',
  billingCredit: '/billing/credit',
  billingProfile: '/billing/profile',
  billingChangePassword: '/billing/change-password',
  billingReports: '/billing/reports',
  billingStockMovements: '/billing/stock-movements',
};

export function masterBusinessesPath({ status, tenant_status } = {}) {
  const params = new URLSearchParams();
  if (status) params.set('status', status);
  if (tenant_status) params.set('tenant_status', tenant_status);
  const query = params.toString();
  return query ? `${PATHS.masterBusinesses}?${query}` : PATHS.masterBusinesses;
}
